---
title: "alberto_implementation"
author: "Niek Brouwer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this document we aim to apply the method developed by Gil-Jimenez et al. to the METABRIC breast cancer cohort. The spatial coordinates and phenotype classification of single cells is retrieved from the paper by Danenberg et al. (2022).

```{r libraries and settings}
library(tidyverse)
library(ggpubr)
library(readxl)
library(reshape2)
library(dbscan)
library(broom)
library(zoo)
library(knitr)
library(NMF,quietly = T)
library(MASS)
library(car)
library(doParallel)
library(foreach)
library(spatstat)
library(raster)
library(gridExtra)

library(ComplexHeatmap)
library(plyr)
library(cold) #function fixeff()
library(lme4)
library(glmmTMB)
library(fitdistrplus)
library(tidyr)

library(magrittr)
library(stats)
library(nlme)
library(dplyr)
library(gridExtra)

source(here("UtilityFunctions.R"))

cells <- getCells()
phenotypes <- get_phenotypes()
n_threads <- parallel::detectCores()
```

## 1-NN distance copmutation


```{r 1-NN distances}


```

## Parameter estimation


```{r parameters}

```


## Fitting NLME model

```{r NLME model}

```

