# Parameter intitialization designed to run in parallel
# Last run: 73876.134 s
# Second run: 31713.034 s

# Required packages for code
library(ComplexHeatmap)
library(tidyverse)
library(plyr)
library(cold) #function fixeff()
library(lme4)
library(glmmTMB)
library(fitdistrplus)
library(tidyr)
library(cold)
library(broom)
library(ggpubr) # stat_compare_means
library(here)
library(fst)
library(tictoc)
library(R.utils)

# Required packages for parallelization
library(doMC)

cores = detectCores()
registerDoMC(cores[1])

###CONFIG
# structure_type <- 'Vascular stroma'
# structure_type <- 'Suppressed expansion'
# structure_type <- 'APC enriched'
# structure_type <- 'Granulocyte enriched'
structure_type <- "TLSlike"

print(structure_type)

distance_data <- paste(here('scratch/AUCScaledSlides_300_'), gsub(' ', '_',structure_type,fixed=T), '.tsv',sep='')
outfile <- paste(here('scratch/init_parameters_'),gsub(' ', '_',structure_type,fixed=T),sep='')

combinations <- readRDS(here('scratch/combinations_selection_run2.rds'))
###


# Directory for intermediate results
if (!dir.exists(paste(here('scratch/init_parameters_'),gsub(' ', '_',structure_type,fixed=T), sep = ''))){
  dir.create(paste(here('scratch/init_parameters_'),gsub(' ', '_',structure_type,fixed=T), sep = ''))
}else{
  message("dir exists")
}

finished_files <- list.files(paste(here('scratch/init_parameters_'),gsub(' ', '_',structure_type,fixed=T),'/', sep = ''))
finished_combinations_int <-  finished_files %>% str_replace("init_params_", "")
finished_combinations_dir <- finished_combinations_int %>% str_replace(".rds", "")
finished_combinations <- unique(finished_combinations_dir)

combinations_selection <- combinations[combinations %in% finished_combinations == FALSE]

message(length(combinations_selection), " combinations: ", combinations_selection)

tic('parameter initialization')

## Recreate 1_NN histograms from coordinates

#comment out, if this is already done and saved as all_combos_dists.rds
all_distances_data <- read_delim(distance_data,delim='\t',
                                 col_types=list(tumor_stroma=col_character()))

all_distances_data <- all_distances_data %>% as_tibble %>%
  mutate(distance_window = WinMean) %>%
  mutate(phenotype_combo = paste(phenotype_from, phenotype_to, sep='_to_')) %>%
  dplyr::select(tnumber, phenotype_combo, `N.per.mm2.scaled`, distance_window) %>%
  mutate(new = `N.per.mm2.scaled` * 1000) %>%
  mutate(new =round(new))

all_combos_dists <- do.call(rbind, mclapply(combinations_selection, mc.cores = 24, function(combi){
  # Recreate 1-NN histogram from coordinates (this is required for function "fitdistrplus")
  dists_onecombi <- tibble()
  message(combi)
  for(tn in unique(all_distances_data %>% pull(tnumber))){
    all_dists_tnum <- list()
    dists <- c(1,all_distances_data %>% filter(tnumber == tn) %>% filter(phenotype_combo == combi) %>% pull(distance_window))
    times <- c(1, all_distances_data %>% filter(tnumber == tn) %>% filter(phenotype_combo == combi) %>% pull(new))

    if(length(times) == 0){
      dists <- c(1:298)
      times <- rep(0,length(c(1:298)))
    }
    for(i in 1:length(times)){
      all_dists_tnum <- c(all_dists_tnum, rep(dists[i], times[i]))
    }
    aldists <- unlist(all_dists_tnum %>% as.numeric)
    aldistsdf <- as_tibble(data.frame(dists = aldists,
                                      tnumber = rep(tn, length(aldists)),
                                      combi = rep(combi, length(aldists))))
    dists_onecombi <- bind_rows(dists_onecombi, aldistsdf)
  }
  return(dists_onecombi)
  }))

saveRDS(all_combos_dists, file = paste(here('scratch/all_combos_dists_'),gsub(' ', '_',structure_type,fixed=T),'.rds', sep = ''))
print('first step complete')



# Use dataset generated by code above
all_combos_dists <- readRDS(paste(here('scratch/all_combos_dists_'),gsub(' ', '_',structure_type,fixed=T),'.rds', sep = ''))

# Run over phenotype ccombinations in parallel
initial_parameters <-mclapply(combinations_selection, mc.cores = 12, function(c){
  message(c)
  # Create empty dataframe for this combination
  initial_params <- data.frame(matrix(ncol=5, nrow=0))
  colnames(initial_params) <- c('term','estimate','std.error', 'tnumber','combo')
  initial_params <- initial_params %>%
    mutate(term=as.character(term), estimate=as.numeric(estimate), `std.error`=as.numeric(`std.error`),tnumber=as.character(tnumber),
           combo=as.character(combo))

  # Loop over all samples
  for(tn in unique(all_combos_dists %>% filter(combi == c) %>% pull(tnumber))){
    # skip vectors that do not have enough datapoints to estimate a Weibull distribution
    tryCatch({
        # Skip tns that take to long to avoid hold-up
        withTimeout({
      params <- fitdist(all_combos_dists %>% filter(combi == c) %>% filter(tnumber == tn) %>% filter(dists < 100) %>% pull(dists), "weibull", lower = c(0, 0)) %>% summary
        }, timeout=6)
      class(params) <- c("fitdist", "fitdistr")
    params <- broom::tidy(params)
    params <- params %>% mutate(tnumber=rep(tn,nrow(params))) %>%
      mutate(combo=rep(c,nrow(params)))

    initial_params <- bind_rows(initial_params, params)

      },error=function(e){})

  }

  # Save intermediate result
  saveRDS(initial_params, paste(outfile,'/init_params_',c,'.rds', sep = ''))

  return(initial_params)

  })

print('initialization done')


toc()

