---
title: "survival_plots"
author: "Niek Brouwer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(glmnet)
library(here)
library(ggplot2)
library(survival)
library(glmnet)
library(survival)
library(survminer)
library(mice)
library(data.table)

source(here("UtilityFunctions.R"))
source(here("MEP_UtilityFunctions.R"))
source(here('logisticRegression_methods.R'))

set.seed(123)
```
```{r}
cells <- getCellsAlternative()
structures <- getStructures()
TMEStructures <- read_fst(here('scratch/TMEStructures.fst'), as.data.table=T)
ptLevelTMEinteractions <- read_fst(here('scratch/ptLeveLTMEInteractions.fst'), as.data.table=T)
NetworkProperties <- readRDS(here('scratch/NetworkProperties.rds'))
clinical_data <- getClinical()
predictors <- predictorInitialFile()
toModel <- apply_filtering(predictors, 100)
clinical_data <- clinical_data %>% dplyr::select(c(metabric_id, `ER Status`, DeathBreast, yearsToStatus))
clinical_data <- na.omit(clinical_data)

ImageMetabricIDs <- cells %>% dplyr::select(c(ImageNumber, metabric_id)) %>% distinct()
toModelWithMetabricID <- merge(toModel, ImageMetabricIDs, by= 'ImageNumber')

TotalDF <- merge(toModelWithMetabricID, clinical_data, by='metabric_id')
colnames(TotalDF) <- gsub('_CPh','',colnames(TotalDF),fixed = T) 
```

```{r}
TMEStructurePredictors <- c("TMEStructure1", "TMEStructure2", "TMEStructure3", "TMEStructure4", "TMEStructure5", "TMEStructure6", "TMEStructure7", "TMEStructure8", "TMEStructure9", "TMEStructure10")

cellPhenotypes <- here('scratch/cellPhenotypeProportionsAlternative.fst')
cellPhenotypes <- read_fst(cellPhenotypes, as.data.table = T)
cellPhenotypes <- cellPhenotypes[grep('tumour|stroma', type)]
cellPhenotypes <- cellPhenotypes[, .(ImageNumber, type, meta_description, proportion)]
allCombinations <- adt(expand.grid(unique(cellPhenotypes[,ImageNumber]), unique(cellPhenotypes[,meta_description])))
setnames(allCombinations, c('ImageNumber', 'meta_description'))
allCombinations <- merge(x = allCombinations, 
                         y = cellPhenotypes[!duplicated(meta_description), .(meta_description, type)], 
                         by = 'meta_description') 
cellPhenotypes <- merge(x = allCombinations, y = cellPhenotypes, 
                        by = c('ImageNumber', 'meta_description', 'type'), all.x = T) 
# cellPhenotypes[, meta_description := paste0(meta_description, '_CPh')]
cPh_tumour <- cellPhenotypes[type == 'tumour', unique(meta_description)]
cPh_tme <- cellPhenotypes[type == 'stroma', unique(meta_description)]

cellPhenotypes <- here('scratch/cellPhenotypeProportions.fst')
cellPhenotypes <- read_fst(cellPhenotypes, as.data.table = T)
cellPhenotypes <- cellPhenotypes[grep('tumour|stroma', type)]
cellPhenotypes <- cellPhenotypes[, .(ImageNumber, type, meta_description, proportion)]
allCombinations <- adt(expand.grid(unique(cellPhenotypes[,ImageNumber]), unique(cellPhenotypes[,meta_description])))
setnames(allCombinations, c('ImageNumber', 'meta_description'))
allCombinations <- merge(x = allCombinations, 
                         y = cellPhenotypes[!duplicated(meta_description), .(meta_description, type)], 
                         by = 'meta_description') 
cellPhenotypes <- merge(x = allCombinations, y = cellPhenotypes, 
                        by = c('ImageNumber', 'meta_description', 'type'), all.x = T) 
cellPhenotypes[, meta_description := gsub("[^A-Za-z0-9+\\-]", "", meta_description)]
cellPhenotypes[, meta_description := paste0(meta_description, '_originalType')]
cPh_tumour_original <- cellPhenotypes[type == 'tumour', unique(meta_description)]
cPh_tme_original <- cellPhenotypes[type == 'stroma', unique(meta_description)]

nwP <- here('scratch/NetworkProperties.rds')
nwP <- read_rds(nwP)
standardiseNwP <- function(name){
  dt <- nwP[[name]]
  setnames(dt, grep('communities_', names(dt), value = TRUE), 'communityID')
  dt[, type := name]
  return(dt)
}
nwP <- rbindlist(lapply(c('stroma', 'tumour'), standardiseNwP))
IDs <- getCells()[, .(ImageNumber, metabric_id)][, .SD[1], by = ImageNumber]
nwP <- merge(x = nwP, y = IDs, by = 'ImageNumber') 
nwP[, assortativity := NULL] #has NAs
measureVars <- grep('ImageNumber|communityID|type|metabric_id', names(nwP), 
                    invert = TRUE, value = TRUE)
PtmeasureVars <- paste0(measureVars, 'PtMean')
nwP[, eval(PtmeasureVars) := lapply(.SD, mean), by = .(type, ImageNumber), .SDcols = measureVars]
nwP <- nwP[, .SD[1], by = .(type, ImageNumber)]
nwP <- nwP[, .SD, .SDcols = c('ImageNumber', 'type', PtmeasureVars)]
nwP <- melt(nwP, id.vars = c('ImageNumber', 'type'))
nwP[, variable := paste0(variable, '_', type)]
nwP <- dcast(nwP, ImageNumber ~ variable)
nwP <- na.omit(nwP)
nwPredictorsTumour <- grep('_tumour', names(nwP), invert = F, value = T)
nwPredictorsTME <- grep('_stroma', names(nwP), invert = F, value = T)

rm(nwP, cellPhenotypes)

shapePredictors <- grep('shape', colnames(toModel), value = T)
scalePredictors <- grep('scale', colnames(toModel), value = T)

```

```{r}
mkCategory <- function(vec, nCats){
   nCats <- 1 / nCats
   cats <- seq(0, 1, nCats)
   out <- cut(vec, breaks = unique(quantile(vec, probs = cats)), 
      labels = F, include.lowest = T)
   return(out)
}

createOrdinalPredictor <- function(df, predictor, categories){
  df <- df %>% mutate(ordinal_predictor = mkCategory(df %>% pull(predictor),categories))
  return(df)
  
}

createBinaryPredictor <- function(df){
  df <- df %>%
  mutate_at(vars(-c('yearsToStatus', 'DeathBreast')), ~ifelse(. > 0.1, 1, 0)) 
  
  # Columns to exclude from casting to factors
  exclude_cols <- c("yearsToStatus", "DeathBreast")
  
  # Cast all columns to factors except for specified columns
  converted_df <- df %>%
    mutate_at(vars(-one_of(exclude_cols)), as.factor)

  return(converted_df)
}

createBinaryPredictorWithMedian <- function(df){
df <- df %>%
  mutate(across(
    setdiff(names(.), c('yearsToStatus', 'DeathBreast')),
    ~as.integer(. >= median(.))
  ))

  # Columns to exclude from casting to factors
  exclude_cols <- c("yearsToStatus", "DeathBreast")
  
  df <- df %>%
  dplyr::select(where(~ !(all(. == 0) || all(. == 1))))
  
  # Cast all columns to factors except for specified columns
  converted_df <- df %>%
    mutate_at(vars(-one_of(exclude_cols)), as.factor)

  return(converted_df)
}

```


## Survival plots
Fit Cox proportional hazards model

```{r}
getRandomColour <- function(n) {
  random_colors <- sample(colors(), n)
  return(random_colors)
}

subsetDF <- function(Dt, ER = NULL){
   if(!is.null(ER)) {
      if(grepl('ositive|\\+', ER)) {
         Dt <- Dt[`ERStatus` == 'Positive']
         suffix <- 'ERpos'
      }else{
         Dt <- Dt[`ERStatus` == 'Negative']
         suffix <- 'ERneg'
      }
   }
   else suffix <- 'AllPts'
   
   return(Dt)
}

cox <- function(df, ER = NULL){
  df <- subsetDF(df, ER)
  predictors <- setdiff(colnames(df), c('ERStatus','yearsToStatus', 'DeathBreast'))

  res.cox <- coxph(as.formula(paste0("Surv(yearsToStatus, DeathBreast) ~ ", paste(predictors, collapse = " + "))), data = df)

  return(res.cox)
    
}

univariateCox <- function(df,predictor, ER = NULL){
    df <- subsetDF(df, ER)
    df <- df %>% rename(predictor_column = predictor)
  res.cox <- coxph(Surv(yearsToStatus, DeathBreast) ~ predictor, data = df)
  return(tidy(res.cox) %>% mutate(term = predictor))
  # return(res.cox)

}

multivariateCox <- function(df, predictors, ER= NULL){
  df <- subsetDF(df, ER)
  x = df %>% dplyr::select(predictors)
  y = Surv(df$yearsToStatus, df$DeathBreast)
  cvfit <- cv.glmnet(as.matrix(x), y, family = "cox")
  
  return(cvfit)
  
}


KMplot <- function(df, predictor, ER= NULL){
  
    Dt <- df %>% rename(predictor_column = predictor)
   if(!is.null(ER)) {
      if(grepl('ositive|\\+', ER)) {
         Dt <- Dt[`ER Status` == 'Positive']
         suffix <- 'ERpos'
      }else{
         Dt <- Dt[`ER Status` == 'Negative']
         suffix <- 'ERneg'
      }
   }
   else suffix <- 'AllPts'
   
   
   bins = unique(Dt$predictor_column)
  fit <- survfit(Surv(yearsToStatus, DeathBreast)  ~ predictor_column, data = Dt)
  if((surv_pvalue(fit,data=Dt) %>% pull(pval)) < 0.05){
      g1 <- ggsurvplot(fit,data=Dt, conf.int = TRUE, pval=T, risk.table = T) + ggtitle(predictor)

  }else{
    g1 <- (paste(predictor, 'is not significant'))
  }


    return(g1)
  
}
```


For all samples.

```{r}
## Survival for density features
densityDF <- TotalDF %>% dplyr::select(all_of(c('ER Status','yearsToStatus', 'DeathBreast', cPh_tumour,cPh_tme)))
colnames(densityDF) <- gsub('+','plus', colnames(densityDF),fixed=T)
colnames(densityDF) <- gsub('-','min', colnames(densityDF),fixed=T)
colnames(densityDF) <- gsub('_','', colnames(densityDF),fixed=T)
colnames(densityDF) <- gsub(' ','', colnames(densityDF),fixed=T)
densityDF <- createBinaryPredictorWithMedian(densityDF)

density_cox <- cox(densityDF)
ggforest(density_cox,data = subsetDF(densityDF))
```

```{r}
densityDF <- TotalDF %>% dplyr::select(all_of(c('ER Status','yearsToStatus', 'DeathBreast',cPh_tme_original, cPh_tumour_original)))
colnames(densityDF) <- gsub('_originalType','', colnames(densityDF),fixed=T)
colnames(densityDF) <- gsub('+','plus', colnames(densityDF),fixed=T)
colnames(densityDF) <- gsub('-','min', colnames(densityDF),fixed=T)
colnames(densityDF) <- gsub('_','', colnames(densityDF),fixed=T)
colnames(densityDF) <- gsub(' ','', colnames(densityDF),fixed=T)
densityDF <- createBinaryPredictorWithMedian(densityDF)

density_cox <- cox(densityDF)
ggforest(density_cox,data = subsetDF(densityDF))
```
## Distance features

```{r}
distanceDF <- TotalDF %>% dplyr::select(all_of(c('ER Status','yearsToStatus', 'DeathBreast', shapePredictors, scalePredictors)))

significant_features <- data.frame(matrix(nrow=0, ncol=5))
for (p in c(shapePredictors, scalePredictors)){
  significant_features <- rbind(significant_features, univariateCox(distanceDF,p))  
}

significant_features <- significant_features %>% filter(p.value < 0.05)

ggplot(significant_features, aes(x = estimate, y = term)) +
  geom_point() +
  geom_errorbarh(aes(xmin = estimate - 2 * std.error, xmax = estimate + 2 * std.error)) +
  geom_text(aes(x=2, y=term, label=format(round(p.value,3), scientific=T)),size=3) + 
  geom_vline(xintercept = 0,linetype='longdash') +
  labs(x = "Coefficient", y = "Variable") +
  theme_minimal()

ggsave(here('output/survival/significantDistanceCoefficients.pdf'),width=9,height=8)
```

```{r}
distanceDF <- TotalDF %>% dplyr::select(all_of(c('ER Status','yearsToStatus', 'DeathBreast', shapePredictors)))
distance_cox <- multivariateCox(distanceDF, shapePredictors)

sds <- apply(toModel, 2, sd)
stdDF <- tibble(var = colnames(toModel), std = sds)

variables <- as.tibble(shapePredictors) %>% mutate(id = rownames(as.tibble(shapePredictors)))

coefList <- as.data.frame(summary(coef(distance_cox,s=distance_cox[["lambda.min"]])))
coefList <- merge(coefList, variables, all.x=T, by.x='i', by.y = 'id') %>% rename(var = value)

coefList <- merge(coefList, stdDF, by='var', all.x=T)

coefList <- coefList %>% mutate(std_val = x * std) %>% dplyr::select(-c('i','j','std'))

```


