---
title: "Feature exploration"
author: "Niek Brouwer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ComplexHeatmap)
library(tidyHeatmap)
library(here)
library(ggplot2)
library(tidyverse)
library(fst)
library(data.table)

source(here("UtilityFunctions.R"))
source(here("MEP_UtilityFunctions.R"))
source(here("figure_styling.R"))

outdir <- here('output/final_figures/Fig4.1/')
```

```{r}
clinical_data <- getClinical()
cell_labels <- alternativeCellTypeLabels()
cell_labels_original <- originalCellTypeLabels()

cells <- getCells()
cellCounts <- getCellCounts(cells)
all_parameters <- getALLParameters()


all_distances_data <- readRDS(file  = here('scratch/AUCScaledSlides_300_ALL.rds'))
all_distances_data <- all_distances_data %>% as_tibble %>%
  mutate(distance_window = WinMean) %>%
  mutate(phenotype_combo = paste(phenotype_from, phenotype_to, sep='_to_')) %>%
  dplyr::select(tnumber, phenotype_combo, `N.per.mm2.scaled`, distance_window) %>%
  mutate(new = `N.per.mm2.scaled` * 1000) %>%
  mutate(new =round(new))

estimated_distances <- all_distances_data %>%
unite('unique_sample', c(tnumber, phenotype_combo), remove=F) %>% filter(unique_sample %in% all_parameters$unique_sample)

cellCombinationCounts <- getCombinationCounts(cells)

cellsAlt <- getCellsAlternative()
cellCountsAlt <- getCellCounts(cellsAlt)
all_parametersAlt <- getALLParametersAlternative()

all_distances_dataAlt <- readRDS(file  = here('scratch/AUCScaledSlides_300_ALL_run2.rds'))
all_distances_dataAlt <- all_distances_dataAlt %>% as_tibble %>%
  mutate(distance_window = WinMean) %>%
  mutate(phenotype_combo = paste(phenotype_from, phenotype_to, sep='_to_')) %>%
  dplyr::select(tnumber, phenotype_combo, `N.per.mm2.scaled`, distance_window) %>%
  mutate(new = `N.per.mm2.scaled` * 1000) %>%
  mutate(new =round(new))

estimated_distancesAlt <- all_distances_dataAlt %>%
unite('unique_sample', c(tnumber, phenotype_combo), remove=F) %>% filter(unique_sample %in% all_parametersAlt$unique_sample)

cellCombinationCountsAlt <- getCombinationCounts(cellsAlt)

```

## Estimation heatmaps

```{r}
all_possible_samples <- cellCombinationCounts %>% filter(n_to >= 5 & n_from >= 20)
samples <- all_possible_samples %>% pull(unique_sample)
all_possibilities_counts <- all_possible_samples  %>% dplyr::count(phenotype_combo) %>%
  separate(phenotype_combo, into=c('phenotype_from','phenotype_to'),sep='_to_', remove = FALSE)

all_parameters_counts <- all_parameters %>% filter(unique_sample %in% samples)  %>% dplyr::count(phenotype_combo) %>%
  separate(phenotype_combo, into=c('phenotype_from','phenotype_to'),sep='_to_', remove = FALSE) %>% rename(n_estimated = n)
all_parameters_counts <- merge(all_parameters_counts, all_possibilities_counts %>% dplyr::select(c(phenotype_combo,n)), all.x=T, by='phenotype_combo') %>% mutate(n_est_p = (n_estimated/(n+1))*100)


all_possibilities_matrix <- reshape2::dcast(all_possibilities_counts,phenotype_to  ~ phenotype_from, value.var = 'n')
rownames(all_possibilities_matrix) <- all_possibilities_matrix %>% pull(phenotype_to)
all_possibilities_matrix <- all_possibilities_matrix %>% dplyr::select(-c(phenotype_to))
all_possibilities_matrix <- all_possibilities_matrix   %>% replace(is.na(.), 0)

all_parameters_matrix <- reshape2::dcast(all_parameters_counts,phenotype_to  ~ phenotype_from, value.var = 'n_estimated')
rownames(all_parameters_matrix) <- all_parameters_matrix %>% pull(phenotype_to)
all_parameters_matrix <- all_parameters_matrix %>% dplyr::select(-c(phenotype_to))
all_parameters_matrix <- all_parameters_matrix   %>% replace(is.na(.), 0)

counts <- cells %>% group_by(meta_description) %>% count()
counts <- merge( tibble(meta_description = rownames(all_parameters_matrix)), counts, by='meta_description') %>% pull(n)
column_ha = HeatmapAnnotation(count = anno_barplot(counts, ylim = c(0,2.5e5)))

rownames(all_parameters_matrix) <- merge( tibble(name = rownames(all_parameters_matrix)), cell_labels_original, by='name') %>% pull(conversion)
colnames(all_parameters_matrix) <- merge( tibble(name = colnames(all_parameters_matrix)), cell_labels_original, by='name') %>% pull(conversion)

hm1 <- Heatmap(all_parameters_matrix, bottom_annotation = column_ha, cluster_rows = T, cluster_columns = T, col=heatmapColorScale(0,794), column_names_gp = grid::gpar(fontsize = 8),
  row_names_gp = grid::gpar(fontsize = 8),column_title = 'phenotype from', row_title = 'phenotype to', column_labels = sapply(colnames(all_parameters_matrix), latex2exp::TeX),row_labels = sapply(rownames(all_parameters_matrix), latex2exp::TeX))
save_pdf(hm1, filename = paste(outdir, 'estimations_orginalClassification_HM.pdf',sep=''),width=7,height=6)
```

```{r}

all_possible_samples <- cellCombinationCountsAlt %>% filter(n_to >= 5 & n_from >= 20)
samples <- all_possible_samples %>% pull(unique_sample)
all_possibilities_counts <- all_possible_samples  %>% dplyr::count(phenotype_combo) %>%
  separate(phenotype_combo, into=c('phenotype_from','phenotype_to'),sep='_to_', remove = FALSE)

all_parameters_counts <- all_parametersAlt %>% filter(unique_sample %in% samples)  %>% dplyr::count(phenotype_combo) %>%
  separate(phenotype_combo, into=c('phenotype_from','phenotype_to'),sep='_to_', remove = FALSE) %>% rename(n_estimated = n)
all_parameters_counts <- merge(all_parameters_counts, all_possibilities_counts %>% dplyr::select(c(phenotype_combo,n)), all.x=T, by='phenotype_combo') %>% mutate(n_est_p = (n_estimated/(n+1))*100)

all_parameters_matrix_alternative <- reshape2::dcast(all_parameters_counts,phenotype_to  ~ phenotype_from, value.var = 'n_estimated')
rownames(all_parameters_matrix_alternative) <- all_parameters_matrix_alternative %>% pull(phenotype_to)
all_parameters_matrix_alternative <- all_parameters_matrix_alternative %>% dplyr::select(-c(phenotype_to))
all_parameters_matrix_alternative <- all_parameters_matrix_alternative   %>% replace(is.na(.), 0)

counts <- cellsAlt %>% group_by(meta_description) %>% count()
counts <- merge( tibble(meta_description = rownames(all_parameters_matrix_alternative)), counts, by='meta_description') %>% pull(n)
column_ha = HeatmapAnnotation(count = anno_barplot(counts, ylim = c(0,2.5e5)))

rownames(all_parameters_matrix_alternative) <- merge( tibble(name = rownames(all_parameters_matrix_alternative)), cell_labels, by='name') %>% pull(conversion)
colnames(all_parameters_matrix_alternative) <- merge( tibble(name = colnames(all_parameters_matrix_alternative)), cell_labels, by='name') %>% pull(conversion)

hm1 <- Heatmap(all_parameters_matrix_alternative,name='No. estimated \n samples', bottom_annotation = column_ha, cluster_rows = T, cluster_columns = T, col=heatmapColorScale(0,794), column_names_gp = grid::gpar(fontsize = 8),
  row_names_gp = grid::gpar(fontsize = 8),column_title = 'phenotype from', row_title = 'phenotype to', column_labels = sapply(colnames(all_parameters_matrix_alternative), latex2exp::TeX),row_labels = sapply(rownames(all_parameters_matrix_alternative), latex2exp::TeX))
save_pdf(hm1, filename = paste(outdir,'estimations_AlternativeClassification_HM.pdf',sep=''),width=7,height=6)
```

## Parameter space

```{r}
mediansAlt <- read_rds(here('scratch/mediansAlt.rds'))
cellCountsPerFeature <- merge(all_parametersAlt, cellCombinationCountsAlt %>% dplyr::select(c(unique_sample, n_from, n_to)), by='unique_sample', all.x=T)
totalCounts <- cellCountsAlt %>% group_by(tnumber) %>% dplyr::summarise(sum = sum(n))
cellCountsPerFeature <- merge(cellCountsPerFeature, totalCounts, by='tnumber') %>% mutate(proportional_nfrom = (n_from/sum)*100) %>% mutate(proportional_nto = (n_to/sum)*100)
cellCountsPerFeature <- cellCountsPerFeature %>% mutate(threshold = ifelse(n_from >= 20 & n_to >= 5, T, F))
cellCountsPerFeature <- merge(cellCountsPerFeature, mediansAlt %>% dplyr::select(c(unique_sample, median_observations)), by= 'unique_sample')

outliersAlt <- read_rds(here('scratch/outlier_parametersAlt.rds')) %>% pull(unique_sample)
below_thresholdAlt <- cellCombinationCountsAlt %>% filter(n_from < 20 | n_to < 5) %>% pull(unique_sample)
```

```{r}
Alberto_parameters <- read_tsv(here('DATA/global_weib_coeff_oct.tsv')) %>% mutate(type='NABUCCO')
Alberto_parameters <- Alberto_parameters %>% separate(phenotype_combo, c('phenotype_from', 'phenotype_to'), sep = '_to_') %>% rename(shape = a, scale = b)

g1 <- ggplot() +
  geom_point(data =cellCountsPerFeature  %>% filter(!(unique_sample %in% below_thresholdAlt)), aes(x=shape, y=scale),size=0.5, alpha=0.1) +
  # geom_density_2d(data =cellCountsPerFeature %>% filter(!(unique_sample %in% outliersAlt))  %>% filter(!(unique_sample %in% below_thresholdAlt)), aes(x=shape, y=scale), color='blue') +
    theme_bw() +
  ylim(10,300) + xlim(0,6) +
  scale_y_log10() +
  xlab('Shape') + ylab('Scale')


g2 <- ggplot() +
  geom_point(data =cellCountsPerFeature %>% filter(!(unique_sample %in% outliersAlt))  %>% filter(!(unique_sample %in% below_thresholdAlt)), aes(x=shape, y=scale),size=0.5, alpha=0.1) +
    geom_point(data =cellCountsPerFeature %>% filter((unique_sample %in% outliersAlt))  %>% filter(!(unique_sample %in% below_thresholdAlt)), aes(x=shape, y=scale,color='outlier'),size=0.5, alpha=1) +
  # geom_density_2d(data =cellCountsPerFeature %>% filter(!(unique_sample %in% outliersAlt))  %>% filter(!(unique_sample %in% below_thresholdAlt)), aes(x=shape, y=scale), color='blue') +
    theme_bw() +
  ylim(10,300) + xlim(0,6) +
  scale_y_log10() +
  xlab('Shape') + ylab('Scale') + guides(colour = guide_legend(override.aes = list(size=10))) + theme(legend.position="bottom")


g3 <- ggplot() +
  geom_point(data =cellCountsPerFeature %>% filter(!(unique_sample %in% outliersAlt))  %>% filter(!(unique_sample %in% below_thresholdAlt)), aes(x=shape, y=scale,colour='METABRIC'),size=0.5, alpha=0.1) +
  geom_point(data =Alberto_parameters, aes(x=shape, y=scale,colour='NABUCCO'),size=0.5, alpha=1) +
    theme_bw() +
  scale_colour_manual(values=c("black","#F8766D" )) +
  ylim(10,300) + xlim(0,6) +
  scale_y_log10() +
  xlab('Shape') + ylab('Scale') + guides(colour = guide_legend(override.aes = list(size=10))) + theme(legend.position="bottom")

allPlots <- plot_grid(g1,g2,g3, nrow = 1)

ggsave(paste(outdir, 'parametersNABUCCOMETABRIC_legend.png',sep=''),width=18,height=6)
```


## combination and sample means

```{r}
# Compute means of each combination
means_combinationsAlt <- all_parametersAlt %>% 
  group_by(phenotype_from, phenotype_to ) %>% 
  dplyr::summarise(mean_shape = mean(shape),
            mean_scale  = mean(scale))

# compute means of each sample
means_imagesAlt <- all_parametersAlt %>% 
  group_by(tnumber) %>% 
  dplyr::summarise(mean_shape = mean(shape),
            mean_scale  = mean(scale))

ggplot() +
  geom_point(data = all_parametersAlt, aes(x=shape, y=scale),color='black', alpha=0.1, size=0.5) +
  geom_point(data = means_combinationsAlt, aes(x=mean_shape, y=mean_scale),color='red',alpha = 0.5, size=1) +
  geom_text(data= means_combinationsAlt %>% filter((mean_shape > mean(means_combinationsAlt$mean_shape) + 2*sd(means_combinationsAlt$mean_shape)) | (mean_shape < mean(means_combinationsAlt$mean_shape) - 2*sd(means_combinationsAlt$mean_shape)) | mean_scale > mean(means_combinationsAlt$mean_scale) + 2*sd(means_combinationsAlt$mean_scale) | (mean_scale < mean(means_combinationsAlt$mean_scale) - 2*sd(means_combinationsAlt$mean_scale))), aes(x=mean_shape,y=mean_scale,label=paste(phenotype_from, phenotype_to, sep='_to_')),color='red',size=2) +  theme_bw() +
  labs(color=NULL) + 
  ylim(10,300) + xlim(0,6) +
  scale_y_log10() +
  xlab('Shape') + ylab('Scale') + ggtitle("METABRIC and combination means")  + 
  guides(colour = guide_legend(override.aes = list(size=10)))

ggsave(paste(outdir,'alternative_classification/', 'parameters_withCombinationMeansAlt.png', sep=''),width=6,height=4)

print(means_combinationsAlt %>% filter((mean_shape > mean(means_combinationsAlt$mean_shape) + 2*sd(means_combinationsAlt$mean_shape)) | (mean_shape < mean(means_combinationsAlt$mean_shape) - 2*sd(means_combinationsAlt$mean_shape)) | mean_scale > mean(means_combinationsAlt$mean_scale) + 2*sd(means_combinationsAlt$mean_scale) | (mean_scale < mean(means_combinationsAlt$mean_scale) - 2*sd(means_combinationsAlt$mean_scale))))

ggplot() +
  geom_point(data = all_parametersAlt, aes(x=shape, y=scale),color='black', alpha=0.1, size=0.5) +
  geom_point(data = means_imagesAlt, aes(x=mean_shape, y=mean_scale),color='red',alpha = 0.5, size=1) +
  geom_text(data= means_imagesAlt %>% filter((mean_shape > mean(means_imagesAlt$mean_shape) + 2*sd(means_imagesAlt$mean_shape)) | (mean_shape < mean(means_imagesAlt$mean_shape) - 2*sd(means_imagesAlt$mean_shape)) | (mean_scale > mean(means_imagesAlt$mean_scale) + 2*sd(means_imagesAlt$mean_scale) | (mean_scale < mean(means_imagesAlt$mean_scale) - 2*sd(means_imagesAlt$mean_scale)))), aes(x=mean_shape,y=mean_scale,label=tnumber),color='red',size=4,position = position_dodge(width = .9)) +
  theme_bw() +
  # labs(color=NULL) + 
  ylim(10,300) + xlim(0,6) +
  scale_y_log10() +
  xlab('Shape') + ylab('Scale') + ggtitle("METABRIC and sample means")
  # guides(colour = guide_legend(override.aes = list(size=10)))

ggsave(paste(outdir,'alternative_classification/', 'parameters_withSampleMeansAlt.png', sep=''),width=6,height=4)
```

## Curve regions with categories

```{r}
cellCountsPerFeature <- merge(all_parametersAlt, cellCombinationCountsAlt %>% dplyr::select(c(unique_sample, n_from, n_to)), by='unique_sample', all.x=T)
totalCounts <- cellCountsAlt %>% group_by(tnumber) %>% dplyr::summarise(sum = sum(n))
cellCountsPerFeature <- merge(cellCountsPerFeature, totalCounts, by='tnumber') %>% mutate(proportional_nfrom = (n_from/sum)*100) %>% mutate(proportional_nto = (n_to/sum)*100)
cellCountsPerFeature <- cellCountsPerFeature %>% mutate(threshold = ifelse(n_from >= 20 & n_to >= 5, T, F))
cellCountsPerFeature <- merge(cellCountsPerFeature, mediansAlt %>% select(c(unique_sample, median_observations)), by= 'unique_sample')

cellCountsPerFeature <- cellCountsPerFeature %>% mutate(shape_q = ifelse(shape < 1.5, 1, ifelse(shape < 2.5, 2, ifelse(shape <4.5, 3, ifelse(shape <10, 4, NA)))))
cellCountsPerFeature <- cellCountsPerFeature %>% mutate(scale_q = ifelse(scale < 30, 1, ifelse(scale < 100, 2, ifelse(scale <300, 3, ifelse(scale < 500, 4, NA)))))

cellCountsPerFeature <- merge(cellCountsPerFeature, resultDF, by.x=c('shape_q','scale_q'), by.y=c('shape', 'scale'))

g1 <- ggplot() +
  geom_point(data =cellCountsPerFeature, aes(x=shape, y=scale,colour=epithelial_epithelial),size=0.5, alpha=1) +
  scale_colour_continuous() +
  scale_colour_gradient2(low="white", high="red", space ="Lab", name='epithelial-epithelial\n percentage' ) +
  theme_bw() +
  ylim(10,300) + xlim(0,6) +
  scale_y_log10() +
  xlab('Shape') + ylab('Scale') + ggtitle("Parameters of epithelial to epithelial combinations ")

g2 <- ggplot() +
  geom_point(data =cellCountsPerFeature, aes(x=shape, y=scale,colour=epithelial_TME),size=0.5, alpha=1) +
  scale_colour_continuous() +
  scale_colour_gradient2(low="white", high="red", space ="Lab", name='epithelial-TME\n percentage' ) +
  theme_bw() +
  ylim(10,300) + xlim(0,6) +
  scale_y_log10() +
  xlab('Shape') + ylab('Scale') + ggtitle("Parameters of epithelial to TME combinations ")

g3 <- ggplot() +
  geom_point(data =cellCountsPerFeature, aes(x=shape, y=scale,colour=TME_epithelial),size=0.5, alpha=1) +
  scale_colour_continuous() +
  scale_colour_gradient2(low="white", high="red", space ="Lab", name='TME-epithelial\n percentage' ) +
  theme_bw() +
  ylim(10,300) + xlim(0,6) +
  scale_y_log10() +
  xlab('Shape') + ylab('Scale') + ggtitle("Parameters of TME to epithelial combinations ")

g4 <- ggplot() +
  geom_point(data =cellCountsPerFeature, aes(x=shape, y=scale,colour=TME_TME),size=0.5, alpha=1) +
  scale_colour_continuous() +
  scale_colour_gradient2(low="white", high="red", space ="Lab", name='TME-TME\n percentage' ) +
  theme_bw() +
  ylim(10,300) + xlim(0,6) +
  scale_y_log10() +
  xlab('Shape') + ylab('Scale') + ggtitle("Parameters of TME to TME combinations ")

g5 <- ggplot() +
  geom_point(data =cellCountsPerFeature, aes(x=shape, y=scale,colour=tumor_TME),size=0.5, alpha=1) +
  scale_colour_continuous() +
  scale_colour_gradient2(low="white", high="red", space ="Lab", name='tumor-TME\n percentage' ) +
  theme_bw() +
  ylim(10,300) + xlim(0,6) +
  scale_y_log10() +
  xlab('Shape') + ylab('Scale') + ggtitle("Parameters of tumor to TME combinations ")

g6 <- ggplot() +
  geom_point(data =cellCountsPerFeature, aes(x=shape, y=scale,colour=TME_tumor),size=0.5, alpha=1) +
  scale_colour_continuous() +
  scale_colour_gradient2(low="white", high="red", space ="Lab", name='TME-tumor\n percentage' ) +
  theme_bw() +
  ylim(10,300) + xlim(0,6) +
  scale_y_log10() +
  xlab('Shape') + ylab('Scale') + ggtitle("Parameters of TME to tumor combinations ")

g7 <- ggplot() +
  geom_point(data =cellCountsPerFeature, aes(x=shape, y=scale,colour=tumor_tumor),size=0.5, alpha=1) +
  scale_colour_continuous() +
  scale_colour_gradient2(low="white", high="red", space ="Lab", name='tumor-tumor\n percentage' ) +
  theme_bw() +
  ylim(10,300) + xlim(0,6) +
  scale_y_log10() +
  xlab('Shape') + ylab('Scale') + ggtitle("Parameters of tumor to tumor combinations ")


p <- addLabelToGrid(plot_grid(g4,g5,g6,g7, ncol=2), 'alternative parameters of TME and tumor relationships')
save_plot(paste(outdir, 'parameterSpace_tumorTME.png',sep=''),p, base_width=10, base_height=8)


```

## Curve extremes

```{r}
outliersAlt <- read_rds(here('scratch/outlier_parametersAlt.rds')) %>% pull(unique_sample)
below_thresholdAlt <- cellCombinationCountsAlt %>% filter(n_from < 20 | n_to < 5) %>% pull(unique_sample)

all_parameters_withoutOutliers <- cellCountsPerFeature %>% filter(!(unique_sample %in% outliersAlt))  %>% filter(!(unique_sample %in% below_thresholdAlt))
n = 40

# Pick extremes
# Divide the curve in areas and pick random from these areas
bottom_right <- sample_n(all_parameters_withoutOutliers %>% filter(n_from > n & n_to > n) %>% filter(phenotype_from != phenotype_to) %>% filter(shape > 5) %>% filter(scale < 20),1) %>% mutate(type= "low scale, high shape")
bottom_left <- sample_n(all_parameters_withoutOutliers %>% filter(n_from > n & n_to > n) %>% filter(phenotype_from != phenotype_to) %>% filter(shape < 2.5) %>% filter(shape >2) %>% filter(scale < 15),1)%>% mutate(type= "low scale, low shape")
mid_right <- sample_n(all_parameters_withoutOutliers %>% filter(n_from > n & n_to > n) %>% filter(phenotype_from != phenotype_to) %>% filter(shape > 2.8) %>% filter(shape <3.5) %>% filter(scale > 200) %>% filter(scale < 300) ,1)%>% mutate(type= "high scale, high shape")
mid_left <- sample_n(all_parameters_withoutOutliers  %>% filter(n_from > n & n_to > n) %>% filter(phenotype_from != phenotype_to) %>% filter(shape < 1.5) %>% filter(scale > 100)%>% filter(scale < 120),1 )%>% mutate(type= "high scale, low shape")
belly <- sample_n(all_parameters_withoutOutliers %>% filter(n_from > n & n_to > n) %>% filter(phenotype_from != phenotype_to) %>% filter(shape < 2.8) %>% filter(shape > 2.6) %>% filter(scale > 80) %>% filter(scale <90),1)%>% mutate(type= "belly")

sample_points <- rbind(bottom_right, bottom_left,mid_right, mid_left, belly)
print(sample_points$phenotype_combo)
stopifnot(nrow(sample_points) ==5)

ggplot() +
  geom_point(data = all_parameters_withoutOutliers, aes(x=shape, y=scale), alpha=0.1, size=0.5) +
  geom_point(data = sample_points, aes(x=shape, y=scale, color=type), alpha=1, size=3) +
  theme_bw() +
  ylim(10,300) + xlim(0,6) +
  scale_y_log10() +
  xlab('Shape') + ylab('Scale')

ggsave(paste(outdir, 'extremeparameters.pdf', sep=''), width=6, height=4)

ggplot() + 
  stat_function(fun = dweibull, args = list(shape = bottom_right$shape, scale = bottom_right$scale), aes(colour='low scale, high shape')) +
  stat_function(fun = dweibull, args = list(shape = bottom_left$shape, scale = bottom_left$scale),aes(colour='low scale, low shape')) +
  stat_function(fun = dweibull, args = list(shape = mid_left$shape, scale = mid_left$scale), aes(colour='high scale, low scale')) +
  stat_function(fun = dweibull, args = list(shape = mid_right$shape, scale = mid_right$scale), aes(colour='high scale, high scale')) +
  stat_function(fun = dweibull, args = list(shape = belly$shape, scale = belly$scale),aes(colour='belly')) + ylim(0,0.2) +
  xlim(0,600) + theme_bw() + xlab('micron') + ylab('N')

ggsave(paste(outdir, 'weibullcurves.pdf', sep=''),width=10, height=4)

sample_distance_data <- merge(x = all_distances_dataAlt %>% filter(tnumber %in% sample_points$tnumber) %>% filter(phenotype_combo %in% sample_points$phenotype_combo),
                              y = sample_points %>% dplyr::select(c(phenotype_combo, shape, scale, type)), all.X =T, by.x='phenotype_combo', by.y='phenotype_combo') 

for (row in 1:nrow(sample_points)){
  slide <- show_distance_distribution(cellsAlt, all_distances_dataAlt, sample_points[row,],0.2)
  slideWithTitle <- addLabelToGrid(slide, title)
  print(slideWithTitle)
  ggsave(paste(outdir,row, '.pdf', sep=''),slideWithTitle, width=10, height=4)
}
```

